from pathlib import Path
import json, re
from urllib.parse import quote
from product_pages import render_product
from html import escape



ROOT = Path(__file__).parent
OUT = ROOT / 'dist'
CONFIG = json.loads((ROOT / 'site-config.json').read_text())
ORIGIN = CONFIG['canonical_origin'].rstrip('/')
EMAIL = CONFIG.get('contact_email', '').strip()
INDEXING_ENABLED = CONFIG.get('indexing_enabled', False)
ROBOTS_POLICY = 'index,follow' if INDEXING_ENABLED else 'noindex,nofollow'
if EMAIL and not re.fullmatch(r'[A-Za-z0-9.!#$%&\'*+/=?^_`{|}~-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}', EMAIL):
    raise ValueError('contact_email must be a valid business email address')
NAV = [('', 'Home'), ('about', 'About'), ('products', 'Products'), ('addvancedfocus', 'AddvancedFocus'), ('mission', 'Mission'), ('contact', 'Contact')]
# The published stylesheet is generated from startup/styles; edit those files, not dist/assets/site.css.
STYLE_DIR = ROOT / 'styles'
STYLE_SOURCES = [
    'tokens.css',
    'base.css',
    'layout.css',
    'components/header.css',
    'components/footer.css',
    'components/buttons.css',
    'components/pills.css',
    'components/cards.css',
    'components/faq.css',
    'components/notice.css',
    'components/closing.css',
    'components/readiness.css',
    'components/page-nav.css',
    'components/steps.css',
    'components/app-icon.css',
    'components/app-mockup.css',
    'components/concept-card.css',
    'components/demo.css',
    'pages/home.css',
    'pages/about.css',
    'pages/products.css',
    'pages/addvancedfocus.css',
    'pages/mission.css',
    'pages/contact.css',
    'pages/product-page.css',
    'media.css',
]
STYLE_HEADER = '/* Generated by generate.py from startup/styles. Do not edit this file. */\n'


def build_stylesheet():
    present = {path.relative_to(STYLE_DIR).as_posix() for path in STYLE_DIR.rglob('*.css')}
    unlisted = sorted(present - set(STYLE_SOURCES))
    missing = sorted(set(STYLE_SOURCES) - present)
    if unlisted or missing:
        raise ValueError(f'startup/styles is out of sync with STYLE_SOURCES. Unlisted: {unlisted}. Missing: {missing}.')
    css = '\n'.join((STYLE_DIR / name).read_text().strip() for name in STYLE_SOURCES)
    (OUT / 'assets' / 'site.css').write_text(STYLE_HEADER + css + '\n')


build_stylesheet()

def link(route):
    return '/' + (route + '/' if route else '')

def section_intro(label, title, body):
    return f'<div class="section-intro"><p class="eyebrow">{label}</p><h2>{title}</h2><p>{body}</p></div>'

def cards(items):
    return '<div class="cards">' + ''.join(f'<article class="card"><span class="card-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>' for i,(title,body) in enumerate(items)) + '</div>'

def cta():
    return '<section class="closing wrap"><p class="eyebrow">HELP SHAPE WHAT COMES NEXT</p><h2>Better support starts<br>with real conversations.</h2><p>Share an everyday challenge, a question, or a perspective that could make our work more useful.</p><a class="button" href="/contact/">Talk with the founder</a></section>'


def future_portfolio():
    items = json.loads((ROOT / 'portfolio.json').read_text())
    rendered = []
    for item in items:
        features = ''.join('<li>' + escape(feature) + '</li>' for feature in item['features'])
        rendered.append(f"""<article class="portfolio-card" id="{item['slug']}" tabindex="-1" aria-labelledby="{item['slug']}-title"><a class="portfolio-image-link" href="/{item['slug']}/" aria-label="Explore {escape(item['name'])}"><img src="/assets/products/{item['slug']}.webp" alt="" width="1536" height="1024" loading="lazy" decoding="async"></a><p class="eyebrow">{escape(item['category'])}</p><h3 id="{item['slug']}-title">{escape(item['name'])}</h3><p class="portfolio-tagline">{escape(item['tagline'])}</p><span class="pill">Future product · Concept development</span><p>{escape(item['description'])}</p><details><summary>Planned capabilities &amp; example<span class="sr-only"> for {escape(item['name'])}</span></summary><div class="portfolio-detail"><h4>Planned capabilities</h4><ul>{features}</ul><h4>An example of the intended experience</h4><p>{escape(item['example'])}</p><h4>Design consideration</h4><p>{escape(item['principle'])}</p></div></details><a class="text-link portfolio-page-link" href="/{item['slug']}/">Explore {escape(item['name'])}</a></article>""")
    return '<section class="section wrap portfolio-section" id="future-products" tabindex="-1" aria-labelledby="portfolio-heading"><div class="section-intro"><p class="eyebrow">THE FUTURE PRODUCT FAMILY</p><h2 id="portfolio-heading">Different needs.<br>One shared commitment.</h2><p>Future products under development, beginning with early concepts. Each addresses a distinct everyday challenge. The capabilities below are planned; these products are not available to use, and release dates have not been set.</p></div><nav class="portfolio-index" aria-label="Future product index">' + ''.join(f'<a href="#{x["slug"]}">{escape(x["name"])}</a>' for x in items) + '</nav><div class="portfolio-grid">' + ''.join(rendered) + '</div></section>'

concept = '''<div class="concept"><div class="concept-top"><strong>AddvancedFocus</strong><span class="pill">Product concept</span></div><p class="muted">A little less to hold. A place to begin.</p><div class="af-mini-horizons" aria-label="Plan horizons"><strong>Now</strong><span>Today</span><span>Upcoming</span><span>Later</span></div><h2>Start smaller.<br>Keep your place.</h2><div class="task"><div><span class="eyebrow">ONE USEFUL STEP</span><strong>Open a blank document.</strong><p>Give it a working title. The rest can wait.</p></div></div><div class="task-meta"><span>2 minutes · Low effort</span><span>At your pace</span></div><a class="text-link" href="/addvancedfocus/#concept-demo">Try the interactive concept</a></div>'''


home = f'''<section class="hero wrap"><div><p class="eyebrow">AI-POWERED ASSISTIVE TECHNOLOGY</p><h1>Life is complex.<br>Support should<br>feel <em>simple.</em></h1><p class="intro">We’re building affordable, accessible apps for neurodivergent people, individuals with disabilities, and families. Starting with AddvancedFocus, our executive-function assistant.</p><div class="actions"><a class="button" href="/addvancedfocus/">Meet AddvancedFocus</a><a class="text-link" href="/mission/">Discover our mission</a></div><p class="micro">AddvancedFocus is in development · Founded in Los Angeles</p></div><div class="hero-visual"><img decoding="async" class="ribbon" src="/assets/hero.webp" alt="" width="1536" height="1024" fetchpriority="high">{concept}<p class="visual-caption">Less to hold in your head.<br>More room to be yourself.</p></div></section><section class="principle-strip"><div class="wrap"><span>Designed around real life</span><span>Privacy as a priority</span><span>You stay in control</span></div></section>
<section class="section wrap">{section_intro('WHY WE’RE HERE', 'The effort behind<br>the everyday.', 'Starting a task. Switching gears. Keeping track of what comes next. We believe technology should help carry that load.')} {cards([('Support that meets you where you are', 'For neurodivergent people, individuals with disabilities, and families navigating the demands of daily life.'), ('Less effort to get going', 'Tools designed to reduce decisions, make the next step clearer, and help turn intention into action.'), ('More room for your life', 'Our goal is practical support that respects your energy, your priorities, and your way of doing things.')])}</section>
<section class="feature-section"><div class="wrap feature"><div><p class="eyebrow">OUR FIRST PRODUCT</p><div class="title-row"><h2>Meet AddvancedFocus.</h2><span class="pill">In development</span></div><p class="large">Help with starting, planning,<br>and keeping everyday life moving.</p><p>Our flagship AI-powered executive-function assistant is being developed to support ADHD, autism, and the everyday work of planning, routines, and household coordination.</p><a class="button" href="/addvancedfocus/">Explore AddvancedFocus</a><p class="micro">Pre-release · Capabilities and availability are still being developed.</p></div><div class="flow-list"><div><span>01</span><h3>Find a starting point</h3><p>Turn a big intention into a manageable first step.</p></div><div><span>02</span><h3>Make a little space</h3><p>Bring plans, routines, and open loops into view.</p></div><div><span>03</span><h3>Begin again, without the guilt</h3><p>Build support around interruptions and changing energy.</p></div></div></div></section>
<section class="section wrap founder-teaser"><div><p class="eyebrow">FOUNDED WITH PURPOSE</p><h2>Technology should<br>adapt to people.</h2></div><div><p class="large">Biro.dev is an early-stage assistive technology company founded by Jonathan Biro in Los Angeles.</p><p>We’re building toward a future where accessible, affordable support is part of everyday life.</p><a class="text-link" href="/about/">Get to know Biro.dev</a></div></section>{cta()}'''

about = (ROOT / 'fragments/about.html').read_text() + (ROOT / 'fragments/company-evaluation.html').read_text() + cta()

products = '''<section class="page-hero wrap"><p class="eyebrow">OUR PRODUCTS</p><h1>Less friction.<br><em>More possibility.</em></h1><p class="intro">A family of AI-powered assistive applications for everyday independence. AddvancedFocus leads the way, with future products taking shape across care, communication, learning, and daily living.</p></section><section class="wrap product-large"><div><span class="pill">Flagship · In development</span><h2>AddvancedFocus</h2><p class="large">An executive-function assistant<br>built around real life.</p><p>We’re developing AI-powered support for getting started, building routines, planning, and managing household responsibilities—with ADHD and autism among the needs informing its design.</p><div class="tags"><span>Task initiation</span><span>Routines</span><span>Planning</span><span>Household mental load</span></div><a class="button" href="/addvancedfocus/">Explore AddvancedFocus</a></div><div class="product-art">''' + concept + '''<p class="micro">Illustrative concept. Not a released interface.</p></div></section><section class="section wrap"><div class="notice"><h2>What you can try. What comes next.</h2><p>AddvancedFocus is not yet publicly available. Release timing, supported platforms, pricing, and final capabilities will be announced when they’re ready.</p><p>AddvancedFocus remains our flagship. The future portfolio below expands our mission to family care, transitions, comprehension, independent living, communication, sensory access, and scam awareness.</p></div></section>''' + cta()

addvancedfocus = '''<section class="wrap af-product-hero"><div><p class="eyebrow">MEET ADDVANCEDFOCUS</p><span class="pill">In development</span><h1>Less deciding.<br><em>More beginning.</em></h1><p class="intro">An AI-powered executive-function assistant being developed for ADHD, autism, and the everyday work of starting, planning, and following through.</p><div class="actions"><a class="button" href="#concept-demo">Try the interactive concept</a><a class="text-link" href="#explore">See the product direction</a></div></div><div class="af-product-promise"><p class="eyebrow">SUPPORT THAT STAYS WITH YOU</p><h2>Find a next step.<br>Make it doable.<br>Know where to return.</h2><p>Keep one action in focus. Give the rest a place to wait. Build a way back when life interrupts.</p><p class="micro">A working illustration of the idea—not a released app.</p></div></section>''' + (ROOT / 'fragments/addvancedfocus-demo.html').read_text() + '''<section id="explore" tabindex="-1" class="section wrap">''' + section_intro('WHAT WE’RE WORKING TOWARD', 'Support for the work<br>behind everyday life.', 'These are AddvancedFocus’s intended areas of support. Specific capabilities are still in development.') + cards([('Starting tasks', 'Turn an intention into one concrete first step, sized to the energy and time available.'), ('Routines that can flex', 'Support everyday sequences while making room for changing schedules, energy, and needs.'), ('Plans that feel manageable', 'Separate Now, Today, Upcoming, and Later so one useful action can stand out without losing the rest.'), ('A lighter household load', 'Explore ways to make responsibilities, follow-ups, and the things people keep in their heads easier to see.'), ('A way back after interruptions', 'Pause with a short return note, preserve the next step, and make re-entry easier after an interruption.'), ('Choice at every step', 'Offer understandable suggestions that people can change or decline. Assistance should strengthen agency.')]) + '''</section><section class="feature-section"><div class="wrap section"><p class="eyebrow">THOUGHTFUL USE OF AI</p><h2>Helpful suggestions.<br>Your decisions.</h2><p class="wide-copy">We’re exploring AI that helps turn loosely described intentions into concrete first steps, simplify plans, and clarify what needs attention. We’re designing around understandable suggestions, clear choices, and respect for personal information. The final AI implementation and data practices will be explained before public release.</p></div></section><section class="section wrap faq"><p class="eyebrow">A FEW THINGS TO KNOW</p><h2>Where things stand.</h2><details><summary>Can I use AddvancedFocus today?</summary><p>You can try the scripted concept on this page today. The full AddvancedFocus application is still in development; a public release date has not been announced.</p></details><details><summary>Who is it being designed for?</summary><p>AddvancedFocus is being developed with neurodivergent people in mind, including people with ADHD and autism, as well as families managing everyday executive-function demands. Individual needs vary; our goal is flexible support.</p></details><details><summary>What will it cost?</summary><p>Pricing has not been set. Affordability is a core product goal, and we’ll share clear pricing before release.</p></details><details><summary>How will personal information be handled?</summary><p>Privacy is a design priority. Specific data collection, storage, AI processing, and user controls are still being defined. We’ll publish those details before people are asked to entrust the product with their information.</p></details><details><summary>Is AddvancedFocus a medical product?</summary><p>AddvancedFocus is being developed for practical everyday support. It is not presented as a diagnostic tool, treatment, or replacement for professional care.</p></details></section>'''

mission = '''<section class="page-hero wrap"><p class="eyebrow">OUR MISSION</p><h1>More agency.<br>Less overwhelm.<br><em>For more people.</em></h1><p class="intro">Develop affordable, accessible applications that help neurodivergent people, individuals with disabilities, and families manage everyday life.</p></section><div class="mission-image wrap"><img src="/assets/hero.webp" alt="" width="1536" height="1024" loading="lazy" decoding="async"><p>Build for possibility.<br>Design for real life.</p></div><section class="section wrap">''' + section_intro('OUR DESIGN COMMITMENTS', 'Care belongs in the details.', 'These principles guide the choices we’re making as we develop our products.') + cards([('Privacy', 'Make clear what information is needed, why it is used, and what choices people have. Define collection, AI processing, retention, and deletion practices before public release.'), ('Affordability', 'Design for practical value at an accessible price. Communicate costs and limits clearly so people can decide whether the product fits their needs and budget. Pricing is still being developed.'), ('User autonomy', 'Make suggestions easy to understand, adjust, and decline. A person should be able to pause, change direction, or decide that a task can wait without being pressured by the product.'), ('Inclusive design', 'Consider cognitive, sensory, and physical needs together. Prioritize clear language, manageable choices, keyboard access, readable interfaces, and control over unnecessary motion.')]) + '''</section><section class="feature-section"><div class="wrap section split"><h2>Accessibility is part<br>of the starting point.</h2><div><p class="large">People shouldn’t have to work harder to get the support they need.</p><p>For this website, that means clear structure, readable contrast, keyboard navigation, responsive layouts, and respect for reduced-motion preferences. Across our products, we aim to make accessibility an ongoing practice.</p><p>Our design target is WCAG 2.2 Level AA. We welcome feedback about anything that makes the experience difficult to use.</p><a class="text-link" href="/accessibility/">Read our accessibility statement</a></div></div></section>'''

contact = (ROOT / 'fragments/contact.html').read_text()

# Report only checks that were actually performed; keep unverified areas explicit.
accessibility_feedback_url = 'mailto:' + escape(EMAIL, quote=True) + '?subject=' + quote('Biro.dev — accessibility feedback')
accessibility = f'''<section class="page-hero wrap"><p class="eyebrow">ACCESSIBILITY STATEMENT</p><h1>Built to be usable.<br><em>Clear about the details.</em></h1><p class="intro">Accessibility is part of how Biro.dev works, including on this website. This statement explains our target, what we have checked, what we have not yet verified, and how to tell us when something gets in your way.</p></section><section class="section wrap">''' + section_intro('OUR TARGET', 'WCAG 2.2 Level AA.', 'The Web Content Accessibility Guidelines 2.2 at Level AA are our design target for this website. This is a goal we work toward, not a certification. The site has not been independently audited, and we do not claim full conformance.') + cards([('Keyboard first', 'Every page has a skip link, visible focus outlines, and a menu you can open, close with Escape, and navigate without a mouse.'), ('Readable and flexible', 'Text and background colors are chosen for strong contrast. Layouts reflow to narrow screens without sideways scrolling, and motion is reduced when your system asks for it.'), ('A demo that waits for you', 'The AddvancedFocus concept never starts a timer on its own. You can pause, stop without marking anything complete, or undo a completion, and status changes are designed to be announced by screen readers.')]) + '''</section><section class="section wrap readiness" aria-labelledby="a11y-review-title"><p class="eyebrow">WHERE THINGS STAND</p><h2 id="a11y-review-title">What we’ve checked so far.</h2><div class="readiness-grid"><article><span class="pill">Reviewed October 8, 2026</span><h3>Checks completed</h3><ul><li>Every page at 320 and 375 pixel widths, with no horizontal scrolling</li><li>One main heading per page, no skipped heading levels, and labeled landmarks</li><li>Text alternatives for informative images</li><li>Calculated text contrast against Level AA thresholds on every page</li><li>Keyboard operation of the menu and the AddvancedFocus demo, including focus placement and announcements</li></ul><p class="micro">Performed in a Chromium-based browser using automated and keyboard checks.</p></article><article><span class="pill">Not yet verified</span><h3>Still to test</h3><ul><li>Screen readers, including VoiceOver, NVDA, and TalkBack</li><li>Additional browsers and physical mobile devices</li><li>Voice control and switch access</li><li>An independent accessibility audit</li></ul><p class="micro">Until these are complete, some barriers may remain.</p></article><article><span class="pill">Known limitations</span><h3>What to be aware of</h3><ul><li>Product mockups and the logo collection are images. The workflow each one illustrates is also described in the page text.</li><li>Contact links open your own email app. The website has no form of its own.</li></ul><p class="micro">These describe this website, not the future applications.</p></article></div></section><section class="feature-section"><div class="wrap section split"><h2>Something not<br>working for you?</h2><div><p class="large">Please tell us. Accessibility feedback directly shapes what we fix next.</p><p>It helps to include the page address, what you were trying to do, and what happened. If you are comfortable sharing it, mention your browser, device, and any assistive technology you use. You do not need to share a diagnosis or other personal health information.</p><a class="button" href="''' + accessibility_feedback_url + '''">Send accessibility feedback</a></div></div></section><section class="section wrap faq"><p class="eyebrow">A FEW THINGS TO KNOW</p><h2>About this statement.</h2><details><summary>Does this statement cover Biro.dev’s future apps?</summary><p>No. It covers this website, including the AddvancedFocus concept demo. Each future application is still in development, and its accessibility approach will be described before public release.</p></details><details><summary>Will this statement change?</summary><p>Yes. We will update it as testing expands and as we fix issues. The review date above shows when it was last checked.</p></details></section>'''


# Distinguish prototype behavior from the product roadmap at a glance.
readiness = '''<section class="section wrap readiness" aria-labelledby="readiness-title"><p class="eyebrow">CLEAR ABOUT THE STAGE</p><h2 id="readiness-title">AddvancedFocus: what’s here today.</h2><div class="readiness-grid"><article><span class="pill">Try in this concept</span><h3>A hands-on illustration</h3><ul><li>Three everyday situations</li><li>Two- and five-minute focus sessions</li><li>Pause, return notes, and next steps</li></ul><a class="text-link" href="/addvancedfocus/#concept-demo">Explore the demo</a></article><article><span class="pill">Product direction</span><h3>Support shaped around you</h3><ul><li>AI-assisted task initiation and planning</li><li>Flexible routines and household coordination</li><li>Privacy, affordability, and user control</li></ul><p class="micro">Capabilities are being developed, not offered as released features.</p></article><article><span class="pill">Not yet announced</span><h3>Details still being decided</h3><ul><li>Public launch date</li><li>Pricing and supported platforms</li><li>Final AI implementation and data practices</li></ul><p class="micro">We’ll explain these before public release.</p></article></div></section>'''
products = products.replace(cta(), (ROOT / 'fragments/product-guide.html').read_text() + future_portfolio() + (ROOT / 'fragments/portfolio-principles.html').read_text() + readiness + cta())
privacy_note = '''<section class="section wrap privacy-note" id="privacy" tabindex="-1"><div><p class="eyebrow">THIS WEBSITE, RIGHT NOW</p><h2>Try the idea.<br>Your notes stay here.</h2></div><div><p>The concept runs in your browser. There is no sign-up, live AI request, analytics script, or marketing cookie in this draft.</p><p>Return notes and example selections stay in page memory. They are not sent anywhere or saved to browser storage, and they disappear when you leave the product page or refresh.</p><p class="micro">This describes the website demo. The future product’s data practices will be published separately before release.</p></div></section>'''
mission += (ROOT / 'fragments/trust-practice.html').read_text() + privacy_note

if EMAIL:
    email_url = 'mailto:' + escape(EMAIL, quote=True)
    contact = contact.replace('{{EMAIL}}', escape(EMAIL)).replace('{{EMAIL_URL}}', email_url)
    for key, subject in [('PRODUCT', 'AddvancedFocus — product feedback'), ('ACCESSIBILITY', 'Biro.dev — accessibility feedback'), ('COMPANY', 'Biro.dev — company inquiry')]:
        contact = contact.replace('{{' + key + '_URL}}', email_url + '?subject=' + quote(subject))
else:
    raise ValueError('A public contact_email is required for this contact page')

home = home.replace(cta(), (ROOT / 'fragments/portfolio-teaser.html').read_text() + cta())
home = home.replace('<section class="section wrap founder-teaser">', (ROOT / 'fragments/home-thesis.html').read_text() + '<section class="section wrap founder-teaser">')
products = products.replace(cta(), (ROOT / 'fragments/development.html').read_text() + (ROOT / 'fragments/portfolio-faq.html').read_text() + cta())
addvancedfocus = addvancedfocus.replace('<section id="explore"', (ROOT / 'fragments/focus-everyday.html').read_text() + '<section id="explore"')
addvancedfocus = addvancedfocus.replace('<section class="feature-section"><div class="wrap section"><p class="eyebrow">THOUGHTFUL USE OF AI</p>', (ROOT / 'fragments/product-intelligence.html').read_text() + '<section class="feature-section"><div class="wrap section"><p class="eyebrow">THOUGHTFUL USE OF AI</p>') + cta()
mission = mission.replace('<div class="mission-image wrap">', (ROOT / 'fragments/mission-practice.html').read_text() + '<div class="mission-image wrap">')
mission += (ROOT / 'fragments/portfolio-principles.html').read_text() + cta()
addvancedfocus = addvancedfocus.replace('<section class="concept-section wrap"', '<figure class="wrap app-mockup"><img src="/assets/products/addvancedfocus.webp" alt="AddvancedFocus concept interface and app icon, showing one small next step and a short focus session." width="1536" height="1024" loading="lazy" decoding="async"><figcaption><span>AddvancedFocus · Interface and logo concept</span><span>Illustrative design. Try the working website prototype below.</span></figcaption></figure><section class="concept-section wrap"')
products = products.replace('<section class="section wrap faq" id="portfolio-questions" tabindex="-1">', '<section class="section wrap brand-family"><div class="section-intro"><p class="eyebrow">ONE FAMILY, DISTINCT IDENTITIES</p><h2>Recognizable support.<br>Made for different moments.</h2><p>Concept app identities for the Biro.dev product family.</p></div><figure class="logo-family"><img src="/assets/products/logo-family.webp" alt="Concept logo collection: AddvancedFocus, CareBridge, StoryReady, ClearCue, PlainPath, StepAble, SayAble, SensoryScout, and OpenCall." width="1536" height="1024" loading="lazy" decoding="async"><figcaption>Exploratory app logos. Product identities may evolve during development.</figcaption></figure></section><section class="section wrap faq" id="portfolio-questions" tabindex="-1">', 1)


products = products.replace('<section class="wrap product-large">', '<section class="wrap product-large" id="flagship" tabindex="-1">')
products = products.replace('</p></section><section class="wrap product-large"', '</p><nav class="page-contents" aria-label="On the products page"><a href="#flagship">Flagship</a><a href="#product-guide">Find your starting point</a><a href="#future-products">Future products</a><a href="#development">Development</a><a href="#portfolio-questions">Questions</a></nav></section><section class="wrap product-large"', 1)

pages = {
 '': ('Technology for everyday possibility', 'Biro.dev is developing affordable, accessible AI-powered applications for neurodivergent people, individuals with disabilities, and families.', home),
 'about': ('About Jonathan Biro & Biro.dev', 'Meet Biro.dev, an early-stage assistive technology company founded by Jonathan Biro in Los Angeles.', about),
 'products': ('Products in development', 'Explore AddvancedFocus and Biro.dev’s future assistive apps for care coordination, communication, comprehension, independent living, and sensory access.', products),
 'addvancedfocus': ('AddvancedFocus — Executive-function support', 'AddvancedFocus is an AI-powered executive-function assistant in development for task initiation, routines, planning, and household mental load.', addvancedfocus),
 'mission': ('Our mission & design commitments', 'Affordable, accessible applications guided by privacy, user autonomy, and inclusive design. Discover Biro.dev’s mission.', mission),
 'contact': ('Contact Biro.dev', 'Connect with Biro.dev, founded by Jonathan Biro in Los Angeles, about accessibility, our mission, and products in development.', contact),
 'accessibility': ('Accessibility statement', 'Biro.dev’s accessibility target for this website, what has been checked, what is not yet verified, and how to report a barrier.', accessibility)
}
portfolio = json.loads((ROOT / 'portfolio.json').read_text())
for item in portfolio:
    pages[item['slug']] = (
        item['name'] + ' — ' + item['category'],
        item['name'] + ': ' + item['tagline'] + ' A future Biro.dev product in concept development. Explore planned capabilities and the intended experience.',
        render_product(item, portfolio, EMAIL)
    )

favicon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='12' fill='%232748c7'/%3E%3Ctext x='12' y='29' fill='white' font-size='29' font-family='sans-serif' font-weight='700'%3Eb%3C/text%3E%3C/svg%3E"
for route, (title, desc, content) in pages.items():
    product_name = next((p['name'] for p in portfolio if p['slug'] == route), 'AddvancedFocus' if route == 'addvancedfocus' else None)
    social_asset = '/assets/products/' + route + '.jpg' if product_name else '/og.jpg'
    social_alt = product_name + ' — illustrative app interface and concept logo.' if product_name else 'Biro.dev — Technology for everyday possibility. Thoughtful AI. More agency. Less overwhelm.'
    social_width, social_height = (1536, 1024) if product_name else (1734, 907)
    nav = ''.join(f'<a href="{link(r)}"'+(' aria-current="page"' if r==route else ' aria-current="location"' if r=='products' and route in {p['slug'] for p in portfolio} else '')+f'>{label}</a>' for r,label in NAV)
    schema = {'@context':'https://schema.org','@type':'Organization','name':'Biro.dev','url':ORIGIN,'description':pages[''][1],'founder':{'@type':'Person','name':'Jonathan Biro'},'location':{'@type':'Place','name':'Los Angeles, California'}}
    schema['email'] = EMAIL
    schema['contactPoint'] = {'@type':'ContactPoint','email':EMAIL,'contactType':'Company inquiries','availableLanguage':'English'}
    page_schema = {'@context':'https://schema.org','@graph':[schema | {'@id':ORIGIN+'/#organization'}, {'@type':'WebSite','@id':ORIGIN+'/#website','url':ORIGIN+'/', 'name':'Biro.dev','publisher':{'@id':ORIGIN+'/#organization'}}, {'@type':'WebPage','@id':ORIGIN+link(route)+'#webpage','url':ORIGIN+link(route),'name':title+' | Biro.dev','description':desc,'isPartOf':{'@id':ORIGIN+'/#website'},'inLanguage':'en-US'}]}
    html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} | Biro.dev</title><meta name="description" content="{desc}"><meta name="robots" content="{ROBOTS_POLICY}"><meta name="theme-color" content="#090f1b"><meta name="color-scheme" content="dark"><link rel="canonical" href="{ORIGIN}{link(route)}"><link rel="icon" href="{favicon}"><link rel="stylesheet" href="/assets/site.css"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:site_name" content="Biro.dev"><meta property="og:title" content="{title} | Biro.dev"><meta property="og:description" content="{desc}"><meta property="og:url" content="{ORIGIN}{link(route)}"><meta property="og:image" content="{ORIGIN}{social_asset}"><meta property="og:image:alt" content="{escape(social_alt, quote=True)}"><meta property="og:image:width" content="{social_width}"><meta property="og:image:height" content="{social_height}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title} | Biro.dev"><meta name="twitter:description" content="{desc}"><meta name="twitter:image" content="{ORIGIN}{social_asset}"><meta name="twitter:image:alt" content="{escape(social_alt, quote=True)}"><script type="application/ld+json">{json.dumps(page_schema)}</script><script src="/assets/concept-model.js" defer></script><script src="/assets/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" aria-label="Biro.dev home" href="/">biro<span>.dev</span></a><button type="button" class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button><nav id="main-nav" aria-label="Main navigation">{nav}</nav></header><main id="main" tabindex="-1">{content}</main><footer class="footer"><div class="wrap footer-top"><div><a class="brand" href="/">biro<span>.dev</span></a><p>Thoughtful technology.<br>Everyday possibility.</p></div><nav aria-label="Footer navigation">{nav}</nav><p>Founded by Jonathan Biro<br>Los Angeles, California<br><a class="footer-email" href="mailto:{escape(EMAIL, quote=True)}">{escape(EMAIL)}</a><br><span class="pill">Products in development</span></p></div><div class="wrap footer-bottom"><span>© 2026 Biro.dev</span><a href="/mission/#privacy">Privacy in this demo</a><a href="/accessibility/">Accessibility</a><span>Made with care. Built for different minds.</span></div></footer></body></html>'''
    directory = OUT / route
    directory.mkdir(parents=True,exist_ok=True)
    (directory/'index.html').write_text(html)

(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: ' + ORIGIN + '/sitemap.xml\n' if INDEXING_ENABLED else 'User-agent: *\nDisallow: /\n')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{ORIGIN}{link(r)}</loc></url>' for r in pages)+'</urlset>')
not_found = (OUT/'index.html').read_text()
not_found = re.sub(r'<meta name="robots"[^>]*>', '<meta name="robots" content="noindex,nofollow">', not_found)
not_found = re.sub(r'<title>.*?</title>', '<title>Page not found | Biro.dev</title>', not_found)
not_found = re.sub(r'<main id="main"[^>]*>.*?</main>', '<main id="main" tabindex="-1"><section class="page-hero wrap"><p class="eyebrow">404 · PAGE NOT FOUND</p><h1>Let’s find your<br><em>way back.</em></h1><p class="intro">This page may have moved. The company and product pages are a good place to start.</p><div class="actions"><a class="button" href="/">Return home</a><a class="text-link" href="/addvancedfocus/">Explore AddvancedFocus</a></div></section></main>', not_found, flags=re.S)
not_found = not_found.replace(' aria-current="page"','')
not_found = re.sub(r'<link rel="canonical"[^>]*>', '', not_found)
not_found = re.sub(r'<meta (?:property="og:[^"]+"|name="twitter:[^"]+")[^>]*>', '', not_found)
not_found = re.sub(r'<script type="application/ld\+json">.*?</script>', '', not_found)
not_found = re.sub(r'<meta name="description"[^>]*>', '<meta name="description" content="This page could not be found. Explore Biro.dev and AddvancedFocus.">', not_found)
(OUT/'404.html').write_text(not_found)

print(f'Generated {len(pages)} pages, 404, sitemap, and configured robots policy.')

legacy = OUT / 'focusflow'
legacy.mkdir(exist_ok=True)
legacy.joinpath('index.html').write_text((OUT/'addvancedfocus/index.html').read_text())
